src/cardb/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import create_user_view
from cardb.views import base_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_view, name='main-page-view'),
    path('cars/', include('cars.urls')),
    path('create_user/', create_user_view, name='create-user-view'),
] + static(settings.STATIC_URL)

src/cars/urls.py
from django.contrib import admin
from django.urls import path

app_name = 'cars'
from cars.views import all_cars_view
from cars.views import create_car_view

urlpatterns = [
    path('', all_cars_view, name='all-cars-view'),
    path('create', create_car_view, name='create-car-view'),
]

src/users/urls.py
from django.contrib import admin
from django.urls import path

app_name = 'users'


urlpatterns = [
    path('admin/', admin.site.urls),
]

src/cars/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class EngineType(models.Model):
    pass

class TransmissionType(models.Model):
    pass

class Car(models.Model):
    #car basic info
    brand = models.CharField(max_length=50)
    carmodel = models.CharField(max_length=50)
    additional_model_info = models.CharField(max_length=100)

    #engine info
    displacement = models.DecimalField(max_digits=10, decimal_places=2)
    # engine type
    power = models.IntegerField()
    #dimensions etc


    #suspension info

    added_by = models.CharField(max_length=150)
    points = models.IntegerField(default=0)

class Label():
    def __init__(self, name, tooltip, required=False):
        self.name = name
        self.tooltip = tooltip
        self.required = required


labels = {
    "Description":{
                "brand": Label("Car brand", "(Subaru)", True),
                "model": Label("Model", "(Impreza)", True),
                "additional_model_info": Label("Additional names", "(WRX STI)")},
    "Engine": {
              "displacement": Label("Engine Displacement", "in cm3", True),
              "power": Label("Engine Power", "in HP", True)},
    "Dimensions": {
                "length": Label("Length", "in mm"),
                "width": Label("Width", "in mm"),
                "height": Label("Height", "in mm"),
                "wheelbase": Label("Wheelbase", "in mm")
    }}

src/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0, blank=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

src/cars/forms.py
from django import forms
from cars.models import Car, labels


class CarCreateForm(forms.ModelForm):
    form = {}
    for field in Car._meta.get_fields():
        form[field.name] = forms.CharField(widget=forms.TextInput(attrs={'class': 'car_input'}))

    class Meta:
        model = Car
        fields = ["brand"]

src/users/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from users.models import Profile
from django.db.models import DateField
from django.conf.global_settings import DATE_INPUT_FORMATS

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('location', 'birth_date')

src/cardb/views.py
from django.shortcuts import render

def base_view(request):
    context = {}
    return render(request, "base.html", context)

src/cars/views.py
from django.shortcuts import render
from cars.models import Car, labels
from cars.forms import CarCreateForm

# Create your views here.
def all_cars_view(request):
    context = {}
    return render(request, "all_cars.html", context)

def create_car_view(request):
    if request.method == "POST":
        pass
    form = CarCreateForm(request.POST)
    labelsdict = {}
    for category in labels:
        labelsdict[category] = {}
        for key, value in labels[category].items():
            labelsdict[category][key] = [labels[category][key].name, labels[category][key].tooltip, labels[category][key].required]

    context = {"form": form, "labels": labelsdict}
    return render(request, "create_car.html", context)

src/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import ProfileForm
from .models import Profile
from django.contrib.auth.models import User

import secrets
import json

# Create your views here.
def create_user_view(request):
    form = UserCreationForm(request.POST)
    pform = ProfileForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            post = request.POST.copy()
            if post['birth_date'] == "":
                post['birth_date'] = "1900-01-01"
            request.POST = post
            form.save()
            pform.save()
            messages.success(request, 'Your profile is created')
            return redirect("create-user-view")

    context = {"form": form, "pform": pform}
    return render(request, "create_user.html", context)

def generate_password():
    return secrets.token_urlsafe(20)

src/cardb/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Car db</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    {% block scripts %}{% endblock %}
</head>
<body>
{% include "menu.html" %}
{{ request.user }}
<br>
{% block content %}
main site
<img src="{% static "/img/birb.png" %}" alt="birb">
{% endblock %}
</body>
</html>

src/cardb/templates/menu.html
<a href="/">Home</a>
<a href="/cars">Cars</a>
<a href="/create_user">Create user</a>
<a href="/cars/create">Create car</a>
{% if user.is_superuser %}
<a href="/admin">Admin</a>
{% endif %}

src/cars/templates/all_cars.html
{% extends "base.html" %}
{% block content %}
all cars
{% endblock %}

src/cars/templates/create_car.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}

<form method="post">{% csrf_token %}
    <table>
    {% for category, values in labels.items %}
        <tr><td><h3>{{ category }}:</h3></td></tr>
        {% for key, value in values.items %}
        <tr>
            <td style="text-align: right">{{ value.0 }}</td>
            <td><input name="{{ key }}"></td>
            <td>{{ value.1 }}</td>
            <script>
                function required() {
                    if ("{{ value.2 }}" == "True") {
                        document.getElementById("{{ key }}").required = true;
                    }
                }
                required();
            </script>
        </tr>
        {% endfor %}
    {% endfor %}
    </table>
    <button type="submit" name="submit">{% trans "Submit" %}</button>
{% endblock %}
</form>

src/users/templates/create_user.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load i18n %}

{% block scripts %}
<script src="{% static '/js/pwd_gen.js' %}"></script>
{% endblock %}
{% if user.is_superuser %}
  	<form action="." method="post">{% csrf_token %}
        <h3>{% trans "Create user:" %}</h3>
        <p><label for="id_username">{% trans "Username:" %}</label></p>
        <p><input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"></p>
        <p>{% trans "150 characters or fewer. Letters, digits and @/./+/-/_ only" %}.</p>
        <p><label for="id_password1">{% trans "Password:" %}</label><input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            <button onclick=pwd_generator()>{% trans "GENERATE" %}</button></p>
            <p><input type="checkbox" onclick="show_pwd()">{% trans "Show Password" %}</p>
            <p>{% trans "Your password can’t be too similar to your other personal information." %}</p>
            <p>{% trans "Your password must contain at least 8 characters." %}</p>
            <p>{% trans "Your password can’t be a commonly used password." %}</p>
            <p>{% trans "Your password can’t be entirely numeric." %}</p>
        <p><label for="id_password2">{% trans "Password confirmation:" %}</label>
        <input type="password" name="password2" autocomplete="new-password" required id="id_password2"></p>
        <p><label for="id_location">{% trans "Location:" %}</label>
        <input type="text" name="location" maxlength="30" id="id_location"></p>
        <p><label for="id_birth_date">{% trans "Birth date:" %}</label>
        <input type="date" name="birth_date" min="1910-01-01" max="2052-12-31" id="id_birth_date">
        <button type="submit">{% trans "Register" %}</button>
    </form>

{% else %}
    <h2>{% trans "Insufficient permissions" %}</h2>
{% endif %}
{% endblock %}